# Generated by Django 2.2 on 2019-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
