# Generated by Django 2.2 on 2019-10-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191019_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='value',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='md5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='salt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='sha1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='sha256',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='first',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='last',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nat',
            name='nat_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='large',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='medium',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='offset',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
